version: '3.3'
services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '7432:7432'
    environment:
      POSTGRES_USER: schisto
      POSTGRES_PASSWORD: schisto
      POSTGRES_DB: schisto
      PGPORT: 7432
      POSTGRES_PORT: 7432
    volumes:
      - ./data/db2:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=schisto && psql --username=schisto --list"
      timeout: 10s
      retries: 4
  web:
    build: .
    command: make run
    volumes:
      - .:/code
    ports:
      - '8081:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://schisto:schisto@db:7432/schisto
