version: '3.3'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8081:8000'
    depends_on:
     - db

  db:
    image: postgres:9.5.6-alpine
    restart: always
    ports:
      - '8001:5432'
    environment:
      POSTGRES_USER: vmesel
      POSTGRES_PASSWORD: vmesel
      POSTGRES_DB: banco

