# Generated by Django 2.0.1 on 2018-01-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelocation',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
