# Generated by Django 4.0.2 on 2022-02-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_smp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSMPSmlinc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_name', models.CharField(blank=True, default='', max_length=2000)),
                ('transcripts_id', models.CharField(blank=True, default='', max_length=2000)),
                ('gene_type', models.CharField(blank=True, default='', max_length=2000)),
                ('is_detected', models.BooleanField(default=False)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.smp')),
            ],
        ),
    ]
