# Generated by Django 4.0.2 on 2022-02-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_clustersmpsmlinc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(blank=True, default='', max_length=2000)),
                ('matrix_name', models.CharField(blank=True, default='', max_length=2000)),
                ('gene', models.CharField(blank=True, default='', max_length=2000)),
                ('enrichment', models.CharField(blank=True, default='', max_length=2000)),
                ('adjusted_p_value', models.CharField(blank=True, default='', max_length=2000)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.smp')),
            ],
        ),
    ]
