# Generated by Django 4.0.2 on 2022-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_clustermatrixdefinitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermatrixdefinitive',
            name='matrix_name_slug',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
