# Generated by Django 4.0.2 on 2022-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0009_clustermatrixdefinitive_matrix_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermatrixdefinitive',
            name='cluster_slug',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
