# Generated by Django 2.0.1 on 2018-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(default='', max_length=256)),
                ('gene_id', models.CharField(default='', max_length=256)),
                ('chromosome_start', models.IntegerField()),
                ('chromosome_end', models.IntegerField()),
                ('strand', models.CharField(default='', max_length=256)),
                ('block_counts', models.IntegerField()),
                ('block_sizes', models.CharField(default='', max_length=256)),
                ('block_starts', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
